### ISSUE TITLE
Geocode 2017 BOE Retailers

### ISSUE THREAD

**Issue by ychaiu** [GreenInfo-Network/Stanford-BOE2017#1]
[boe2017_12.xlsx](https://github.com/GreenInfo-Network/Stanford-BOE2017/files/1624161/boe2017_12.xlsx)

From Amanda: This is a list of stores we need to geocode for Stanford. We should use the ESRI street layer and track the match rate. We need the location to be by address, not allow a city/zip or other less accurate match be assigned.  It will take credits from ESRI which is fine - we can try and sort out the cost to pass through to the client.

Bill to the root of Stanford PRC in QB ($70) - as I still need to sort out the new billing jobs we will need in 2018.

**Comment by ychaiu** [comment]
P:\proj_p_s\Stanford_PRC\BOE_2017\data\BOE2017_12_Geocoding_Results.shp

33,046 Addresses

Score>=90 : 32,687 (98.9%)
90>Score>=80 : 321 (0.97%)
Score<80 : 38 (0.1%)

Sorting by ascending order in the matched address fields shows that are roughly 274 records that were matched to non-specific street/city/zip.

**Comment by AmandaGIN** [comment]
AR reviewed 45 records with a score less than 82.  Included notes on if they were moved, found, not changed, etc.

Basic approach:
Descending sort on Score from geocode
Use Google Maps to locate (search on combos of name and address, as available) looking for confirmation of store (some cases dropped into street view).
Note the final determination of the geocode quality/result/changes.

Generate file of stores for BOE 2017 with current date at end. This is the file to copy/edit if changes are made in the future.
- Remove store in Ohio (FLAVORSS15 LLC, FLAVORS UNITED, 4215 Lyons Rd, Miamisburg, OH 45342, License 91389030).
- Remove store in Nevada (VAPETASIA, LLC, VAPETASIA, LLC, 3990 W RUSSELL RD STE 8, NV 89118, License 91389530).
- Remove unnecessary attribute fields, they could be joined back but are likley not needed.
- Add lat/long
- Add county (name and fips)
- Add city (name and fips)

**Comment by AmandaGIN** [comment]
Evaluated possible improvements on store locations:
- 2 "Review - matched to street name & different postal code" The geocode is only to the street name & the zip code is different from the reported store zip code.
- 78 "Review - different postal code" The geocoded zip code is different from the reported store zip code.
- 24 "Review - matched to street intersection"
- 229 "Review - match to street name" The geocode is only to the street name
- 23 "Review - matched to POI" The geocode was done based on Point Of Interest
- 195 "Review - score under 90"

**Comment by AmandaGIN** [comment]
Final shapefile as of 1/17/2018:
P:\proj_p_s\Stanford_PRC\BOE_2017\data\BOEe2017_2018_01_17.shp
with summary table for client produced & saved in same folder:
BOE2017_withCityCountyLongLat_2018_01_17.xlsx
[BOE2017_withCityCountyLongLat_2018_01_17.xlsx](https://github.com/GreenInfo-Network/Stanford-BOE2017/files/1640722/BOE2017_withCityCountyLongLat_2018_01_17.xlsx)
