### ISSUE TITLE
Demographic Gathering

### ISSUE THREAD

**Issue by AmandaGIN** [GreenInfo-Network/Stanford-BOE2017#6]
ACS 2012-16 is the latest but not yet ready on the [geospatial site.](https://www.census.gov/geo/maps-data/data/tiger-data.html) Manually produced from American FactFinder for all CA Census Tracts.

- [x] Age_0_17
- [x] Age_5_17
- [x] Age_18_20
- [x] Age_21_24
- [x] NHL_AfAmer
- [x] NHL_Asian
- [x] NHL_PI
- [x] NHL_White
- [x] NHL_AInd
- [x] NHL_Other
- [x] NHL_2plus
- [x] HisLat
- [x] MHHI
- [x] Pov_185pct
- [x] HH_cnt
- [x] Area_sqmi

**Comment by AmandaGIN** [comment]
For MHHI
250001 = those tracts with over 250,000 (250000+ from AFF)
-999999999 = no MHHI for tract, no Population (MHHI is - from AFF; TotPop = 0 from AFF)
-888888888 = no MHHI from tract, BUT tract has a Population

**Comment by AmandaGIN** [comment]
for Poverty `PopPov_Chk` `InPoverty` `PctInPov` `PovLev_185pct`
-999999999 = No Data: no one was asked about poverty PovPop_chk was 0 (HC01_EST_VC01: Total; Estimate; Population for whom poverty status is determined)
 
A 0 in the `InPoverty` `PctInPov` and `PovLev_185pct` are true 0's

**Comment by AmandaGIN** [comment]
with Housing, verifed a few that had a large population but 0 housing units.
Examples: 06037403200 is a Pomona community Conserv Corp housing 
06071012300 is a mental hospital
*I believe these type are covered by group housing, not housing units.

**Comment by AmandaGIN** [comment]
Land area is taken from the Census reported ALAND AWATER (sq meters).
Conversions to both Square Miles and Acres are in the file.

**Comment by AmandaGIN** [comment]
Flagged tracts with 0 population and 0 land for removal.

**Comment by AmandaGIN** [comment]
@ychaiu please download all of the listed variables (at top) for the block group level from:
https://www.census.gov/geo/maps-data/data/tiger-data.html

Create one final feature class/shp with attributes we will need
Remove above notes for data concerns (non reported data, and/or values at min/max, etc)

**Comment by ychaiu** [comment]
- downloaded all the attributes except for "total population below 185% FPL." -- this data table is able at the census tract level, not block group

- will need to project the shp to calculate acres. What projection should we use?

P:\proj_p_s\Stanford_PRC\BOE_2017\data\DemographicAnalysis\BOE2017_DemographicAnalysis.gdb\ACS_2016_5YR_BG_06_CA

**Comment by AmandaGIN** [comment]
Added `ALAND` and `AWATER`
Calculated square miles of the full block group (land & water) `AreaSqMi`

**Comment by AmandaGIN** [comment]
185% Poverty is only available at the tract level.
Source: S1701, Poverty Status in the Past 12 Months:  All Individuals with Income Below the Following Poverty Rations: 185 percent of poverty level [HC01_EST_VC55]

Factored it to the block group:
FIELD 1- Below Poverty, block-group `Bl_Pov_Ind`
FIELD 2 - Below Poverty, tract `Bl_Pov_IndTract`
FIELD 3 - `Bl_Pov_Ind` / `Bl_Pov_IndTract` = `PctofTractPoverty`
FIELD 4 - Count of those Below 185% Poverty, Tract = `Tract185PovInd`
FIELD 5 - `Tract185PovInd` * `PctofTractPoverty` = `Est185PovertyBlockGroup`

Results:
12,332,300
compared to Tract total of 12,332,794 (confirmed on AFF 12,332,794)
Difference 494 (0.004%)
