### ISSUE TITLE
Network Analyst

### ISSUE THREAD

**Issue by ychaiu** [GreenInfo-Network/Stanford-BOE2017#9]
- Downloaded and installed StreetMap Premium
- Network Analysis notes: "P:\proj_p_s\Stanford_PRC\BOE_2017\data\NetworkAnalysis\NetworkAnalysisNotes_Jan2018.docx"
- Routing datasets stored in C:\Users\Gorgonio.GREENINFO\Documents\StreetMapPremium\NAHR_2017R2_FGDB\FGDB\StreetMap_Data\NorthAmerica.gdb\Routing
- Used existing "Routing_ND" (previous attempts with my own network did not work, only resulted in 5,428 solved routes)
- Unable to solve the network with "Closest Facility," but created an OD Matrix Layer that does the same analysis (looks at the closest distance on the network, but produces straight lines from origin to destination)
- For origins (schools), the analyst can only take points, not polygons. Used the centroids from CSCD, using schools from CCHAT (10044)
- Added destinations (all BOE facilities: 33044)
- network solved with 10044 routes created. There is a "Miles" attribute that measures distance between a school and the closest retailer on the network
- 10044 service area layers created for 1/2 mile distance of schools

**Comment by ychaiu** [comment]
Schools
[CSCD_2016_publicSchools_K12_centroids.zip](https://github.com/GreenInfo-Network/Stanford-BOE2017/files/1768467/CSCD_2016_publicSchools_K12_centroids.zip)

Retailers
[BOE2017_2018_01_17.zip](https://github.com/GreenInfo-Network/Stanford-BOE2017/files/1768468/BOE2017_2018_01_17.zip)

OD Matrix Routes
[SMP_RoutingND_OD_Cost_Matrix_Lines.zip](https://github.com/GreenInfo-Network/Stanford-BOE2017/files/1768471/SMP_RoutingND_OD_Cost_Matrix_Lines.zip)

Service Area Half-Mile Schools
[SMP_RoutingND_Schools_ServiceArea_HalfMile.zip](https://github.com/GreenInfo-Network/Stanford-BOE2017/files/1768480/SMP_RoutingND_Schools_ServiceArea_HalfMile.zip)

Service Area Half-Mile Retailers
[SMP_RoutingND_Retailers_ServiceArea_HalfMile.zip](https://github.com/GreenInfo-Network/Stanford-BOE2017/files/1768483/SMP_RoutingND_Retailers_ServiceArea_HalfMile.zip)

**Comment by AmandaGIN** [comment]
@ychaiu 
Explore if we are able to use Network Analyst to find all retailers within 1/2 mile (on roadway).
We would need it to report:
School CDS_Unique
License Number
Distance to (on road)

May not be possible and/or to much CPU needed to solve.

**Comment by AmandaGIN** [comment]
@ychaiu 
Using this file you created (1/2 mile of retailer)
Service Area Half-Mile Retailers
SMP_RoutingND_Retailers_ServiceArea_HalfMile.zip
Find the count of schools within each polygon
Use a spatial join - but you'll need to use ArcToolBox to allow for a One-to-Many join

Run this analysis twice
- [x] Use school centroids
CSCD_2016_publicSchools_K12_centroids.zip

Try the SJ but if doesn't work on poly files use Intersect or Union.
- [x] Use school boundary file (stacked polygons)
excract from CSCD using the centroid list 

Then summarize:
Sheet 1 - Count of schools per retailer
Sheet 2 - List of each retailer, repeat and then list school
Sheet 3 - Matrix of retailer, and rows of schools (I can show you how to do in gSheets Unique, Transpose, Filter)

**Comment by AmandaGIN** [comment]
Can you also review the draft table I'll be sending Nina for any oddities:
https://www.dropbox.com/s/2b4ywz2pbni13yj/Schools_to_Retailers_HalfMileNetworkAndEuclidean.xlsx?dl=0

**Comment by ychaiu** [comment]
[Retailers_Service_Area_Schools_Summary.xlsx](https://github.com/GreenInfo-Network/Stanford-BOE2017/files/1795231/Retailers_Service_Area_Schools_Summary.xlsx)

School Centroids
- SJ of school centroids to service areas (one to many)
- ran analysis twice, checked uniqueness of service area id to school centroid
- summarized on licensenum field to obtain count of schools in each service area
- 27,825 schools in total

Stacked School Boundary
-  Used N:\California\Schools\CSCD\CSCD_2016\CSCD_2016.gdb\CSCD_2016.gdb\Schools\Schools_Current_Stacked, selected those used in original analysis (10044 schools)
- SJ of stacked polygons to service areas (one to many)
- ran analysis twice, checked uniqueness of service area id to polygon (CDS_uniq)
- summarized on licensenum field to obtain count of schools in each service area
- 46,850 schools in total

Wasn't able to create the matrix since dataset was too large for import into Gsheets. Know of any other way to do this in Excel?

**Comment by ychaiu** [comment]
Retailers in 1/2 mile school service area

https://docs.google.com/spreadsheets/d/1OofYpsJ6HR-m5y89QzR3laxTtpzbdYkwGlLU2aZGv0U/edit#gid=0

**Comment by ychaiu** [comment]
[Schools_ServiceArea_HalfMile_Retailers_Ranked.xlsx](https://github.com/GreenInfo-Network/Stanford-BOE2017/files/1797908/Schools_ServiceArea_HalfMile_Retailers_Ranked.xlsx)

Limited max stores (65) for each service area
SMP - OD cost matrix, set to find closest 65 
Filter those out over 0.5 mile
Add rank (python script)

**Comment by ychaiu** [comment]
Yessenia

Run service area analysis with SMP dataset with following properties:

No hierarchy (to reduce generalization and reduce capturing roads that aren't traversable)
Detailed polygons (to reduce holes that don't capture the network)

**Comment by AmandaGIN** [comment]
Given errors in Service Areas, the previous summary of retailer (point) to school (point/centroid)  had 27,825 schools within a half-mile. This is 59 too many and is from the polygon extensions in populated areas.
![image](https://user-images.githubusercontent.com/11776169/38387926-715ff3c2-38ce-11e8-97d8-bd0c88c3aee9.png)

To fix this, the OD matrix results were used instead. There are 27,766 school centroids within a half-mile of a retailer point when traveling the street network using SMP.
